name: grcov

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to codecov.io
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          DOWNLOAD_URL=`curl -s 'https://api.github.com/repos/xd009642/tarpaulin/releases/latest' | jq -r '.assets[0].browser_download_url'`
          echo "Downloading tarpaulin from $DOWNLOAD_URL"
          curl -L "$DOWNLOAD_URL" --output tarpaulin.tgz
          tar xzf tarpaulin.tgz
          ./cargo-tarpaulin tarpaulin --out Xml
          bash <(curl -s https://codecov.io/bash) -X gcov -t $CODECOV_TOKEN